### ISSUE TITLE
EEE Roadmap: Embrace existing DNS APIs

### ISSUE THREAD

**Issue by coolaj86** [dashhive/webdns#1]
Typically Name Server (NS) records are all (typically 2-4) set to the same provider.

This is politically dangerous. We want the ability to set Name Servers in a non-homogenous (heterogeneous) fashion - such that some are set with one provider, and others with another. That's the goal anyway.

As a first step we need to take a "libdns" approach that allows us to set records on the following providers:

- [ ] Digital Ocean DNS API
- [ ] Cloudflare DNS API
- [ ] GoDaddy DNS API

GoDaddy is included even though it's tied to specific, purchased domains because they're one of the top registrars, so we'll have to interface with their API at some point regardless.
